- src/components/FocusCard.tsx
- src/components/MapSection.tsx
- src/data/placesData.ts
- src/types/place.ts
- MapSection -> FocusCard 분리
- placesData.tsx -> .ts 변경
- place.ts 타입 정의 파일 생성
> Refactor: 컴포넌트 분리

- src/App.tsx
- src/components/DashboardDemo.tsx
- tsconfig.json
App.tsx [ About -> DashboardDemo ]
> Feat: DashboardDemo 구현

- src/components/Admin.tsx
- src/components/DashboardDemo.tsx
- src/components/FocusCard.tsx
> Fix : 에러 수정

- src/App.tsx
- src/components/Dashboard.tsx
- src/components/DashboardDemo.tsx
- src/components/dashboard/ActionButton.tsx
- src/components/dashboard/ChartCard.tsx
- src/components/dashboard/POICardList.tsx
- src/components/dashboard/ParkingInfoCard.tsx
- src/components/dashboard/PlaceInfoCard.tsx
- src/components/dashboard/ReviewAnalysisCard.tsx
- src/components/dashboard/TrafficInfoCard.tsx
- src/components/dashboard/VisitorCountCard.tsx
- src/components/dashboard/WeatherCard.tsx
대시보드 내 카드 각 컨포넌트로 분리
- /components/dashboard/*.tsx
- DashboardDemo -> Dashboard 변경
> Refector: Dashboard 분리

- src/components/stars/DashboardComponent.tsx
- src/components/stars/dashboard/ActionButton.tsx
- src/components/stars/dashboard/ChartCard.tsx
- src/components/stars/dashboard/ParkingInfoCard.tsx
- src/components/stars/dashboard/PlaceInfoCard.tsx
- src/components/stars/dashboard/ReviewAnalysisCard.tsx
- src/components/stars/dashboard/TrafficInfoCard.tsx
- src/components/stars/dashboard/VisitorCountCard.tsx
- src/components/stars/dashboard/WeatherCard.tsx
> Refactor: 대시보드 카드 수정

- src/components/stars/map/FocusCard.tsx
> Refactor : CSS 수정

- src/components/stars/map/FocusCard.tsx
> Refactor : 모션 최적화

- src/components/stars/dashboard/ActionButton.tsx
- src/components/stars/dashboard/ChartCard.tsx
- src/components/stars/dashboard/CongestionStatusCard.tsx
- src/components/stars/dashboard/DashboardComponent.tsx
- src/components/stars/dashboard/POICardList.tsx
- src/components/stars/dashboard/ParkingInfoCard.tsx
- src/components/stars/dashboard/PlaceImageCard.tsx
- src/components/stars/dashboard/PlaceInfoCard.tsx
- src/components/stars/dashboard/ReviewAnalysisCard.tsx
- src/components/stars/dashboard/TrafficInfoCard.tsx
- src/components/stars/dashboard/VisitorCountCard.tsx
- src/components/stars/dashboard/WeatherCard.tsx
> Refactor: 반응형 대시보드 적용

- index.html
- src/components/stars/map/MapSectionComponent.tsx
- src/index.css
- src/layouts/FullPageLayout.tsx
- src/utils/setAppHeight.ts
> Feat: 모바일 환경에서의 높이 조절 기능 추가

- src/components/stars/dashboard/DashboardComponent.tsx
- src/components/stars/dashboard/ReviewAnalysisCard.tsx
* AI리뷰분석 Dummy PieChart로 변경
* 맵으로가기 및 위로이동 버튼 색상 통일
> Refactor: PieChart로 변경

- package-lock.json
- src/components/Home/Home.tsx
- src/components/admin/AdminLogin.tsx
- src/components/stars/map/MapSectionComponent.tsx
- src/index.css
- src/layouts/FullPageLayout.tsx
> Feat: Home Login 기능 추가

- src/components/login/LoginForm.tsx
- src/components/stars/map/MapSectionComponent.tsx
* 로그인 시 navigate [manage -> map]
* MapSection 검색창 재사용
> Refactor: 검색창 재사용

- src/components/admin/AdminComponent.tsx
- src/components/admin/AdminDetail.tsx
- src/components/admin/AdminHeader.tsx
- src/components/admin/AdminTour.tsx
- src/components/user/Favorite/UserFavorite.tsx
- src/components/user/Info/UserInfo.tsx
- src/components/user/Info/UserInfoEdit.tsx
- src/components/user/Info/UserInfoShow.tsx
관리자, 사용자 마이페이지 axios 통신을 위한 준비 완료
일정확률로 실패해서 오류가 발생할 때 경우도 생성해두었습니다
> PR : axios 통신 준비 2

- src/api/starsApi.tsx
> Refactor: prefix 수정

- src/components/login/RegisterForm.tsx
- src/hooks/useCustomLogin.tsx
> Refactor: 로직 개선

- src/api/mypageApi.tsx
- src/components/user/Info/UserInfo.tsx
- src/components/user/Info/UserInfoEdit.tsx
- src/data/UserInfoData.ts
회원정보 수정 로직이 바뀜에 따라 회원 비밀번호를 변경하는 로직을 바꿨습니다. 
API에 암호를 넣지 않으면 기존 암호를 그대로 유지하며, 암호를 변경하고자 하면 기존 암호, 신규 암호를 전부 보내야합니다
> PR : 회원정보 수정 기능 추가

- src/api/adminApi.tsx
- src/api/starsApi.tsx
- src/components/admin/AdminComponent.tsx
- src/components/admin/AdminTour.tsx
- src/components/admin/AdminUserFavorite.tsx
- src/data/adminData.ts
각종 행사 정보들의 정보를 가져오고, 정리를 해주는 컴포넌트 제작 완료
ㄴ 유/무료 구분은 가능하나 정확한 가격 정보까지는 뜨지 않고있음, 개선사항
관리자 권한을 가진 계정의 token을 가진 상태에서 접속하면 각종 유저들이 등록한 즐겨찾기를 조회한다. 
ㄴ 이름을 검색할 수 있는 창을 만들긴 했는데, 모든 데이터를 가져온 뒤에 그 안에서 찾는 구조라 궁극적인 검색 구조가 아님
ㄴ 관광지 종류마다 배지나 색깔을 다르게 해서 구분할 수 있도록 함
> PR : 관리자 페이지 행사, 즐겨찾기 조회 API 연결

- src/api/authApi.tsx
- src/components/admin/AdminComponent.tsx
- src/components/admin/AdminDetail.tsx
- src/components/admin/cards/CongestionTag.tsx
- src/components/user/Info/UserInfo.tsx
관리자 대시보드에서 관광지 정보 조회 가능
ㄴ 문제는 상세보기 갔다가 오면 정보를 다시 받아와야하는 문제가 있음, 그래서 상위 컴포넌트에서 sse 구독 처리를 한 뒤에 가져오는 방식을 생각중
> PR : 관리자 대시보드 관광지 정보 로드 구현

- src/api/starsApi.tsx
- src/components/stars/map/AreaFoucsCard.tsx
- src/components/stars/map/MapSectionComponent.tsx
- src/context/PlaceContext.tsx
*refactor: area_id (string -> number) 수정
> refactor: 지역(관광특구) 기반 마커 호출

- src/components/admin/AdminComponent.tsx
- src/components/admin/AdminContainer.tsx
- src/components/admin/AdminDetail.tsx
- src/components/admin/AdminHeader.tsx
- src/components/user/Info/UserInfo.tsx
- src/context/AdminContext.tsx
- src/data/adminData.ts
- src/routes/AppRoutes.tsx
관리자 페이지 component들의 잦은 갱신으로 SSE통신이 계속 초기화 되는 문제가 발생하여 너무 잦은 데이터 fetch가 발생
-> 상위 컨테이너 역할을 하는 Provider를 이용해 상위에서 SSE 연결을 담당하고, 하위에선 받아오는 방식으로 변경
현재 SSE부분은 관광지정보, 혼잡정보만 처리 완료하였으며, 행사정보, 즐겨찾기 정보는 SSE를 사용하지 않고 있으므로 별도 조치를 취하지 않았음
차후 날씨, 교통, 주차 정보까지 연동 진행할 예정
> PR : AdminComponent 컨테이너화

- .github/workflows/deploy.yml
- src/components/alert/AlertModal.tsx
- src/components/stars/map/MapSectionComponent.tsx
- src/components/stars/map/Menu.tsx
> Refactor: 로그인 로그아웃 버튼 메뉴로 이동

- src/components/stars/dashboard/CongestionStatusCard.tsx
- src/components/stars/dashboard/DashboardComponent.tsx
- src/components/stars/dashboard/VisitorCountCard.tsx
+ VisitorCountCard 유동 인구 수 텍스트 색상 동기화
* DashboardComponent 람다 함수 매개변수 타입 명시
> feat: 현재 유동 인구 수 색상 동기화

- src/components/admin/AdminTraffic.tsx
- src/context/AdminContext.tsx
- src/data/adminData.ts
기존 교통혼잡 데이터만 표시되었는데 주차장 정보도 추가하여 마커로 표시되도록 구현
마커 삭제도 정상 작동중
> PR : 관리자 지도 화면 교통혼잡과 주차장 정보 추가

- src/components/admin/AdminUserFavorite.tsx
- src/components/admin/cards/FavoriteCard.tsx
- src/components/admin/cards/UserList.tsx
FavoriteCard와 UserList 를 분리하여 중복을 제거하였고 props로 전달받도록 하였음.
전체 즐겨찾기 순위 구현을 통해 관리자가 더욱 관제하기 용이하도록 함
> Feat: 관리자 즐겨찾기 전체순위 구현

- src/components/admin/AdminTraffic.tsx
- src/components/stars/map/MapSectionComponent.tsx
메인지도 : 네비게이션컨트롤 추가 -> 조작성 상승
관리자 지도 : 지도 단색화 & 도로 끝점 삭제 -> 가시성 상승
> PR : 지도 기능 추가 및 수정

- src/components/user/Info/UserInfo.tsx
- src/components/user/Info/UserInfoShow.tsx
- src/components/user/MyPage.tsx
기본에 형편없는 디자인에서 그나마 봐줄법한 디자인으로 수정
수정하면서 지도로 돌아가는 버튼을 지도에 있는 마이페이지 이동 버튼과 통일
> PR : 마이페이지 디자인 기본 틀 구현 및 회원정보 컴포넌트 디자인 수정

- src/components/admin/TrafficMapComponent.tsx
- src/components/test/test.tsx
- src/context/AdminContext.tsx
- src/routes/AppRoutes.tsx
관리자 도로교통상황을 볼 수 있는 지도를 컴포넌트화하여 다른 곳에서도 카드처럼 사용할 수 있도록 변경
사용시 같은 area_id를 공유하는 TrafficData와 ParkData를 넣으면 해당 정보에 있는 LngLat를 사용하여 도로 교통현황 및 주차징 위치를 표시한다
> PR : 관리자 도로교통상황 지도 컴포넌트화

- src/components/admin/AdminTraffic.tsx
- src/components/stars/map/MapSectionComponent.tsx
- src/components/user/Favorite/UserFavorite.tsx
- src/context/AdminContext.tsx
사용자 즐겨찾기 디자인 변경
관리자모드 더미데이터 불러오는 설정 철회
모든 교통혼잡 불러오는 기능 추가해봤으나 렉이 너무 심한 관계로 포기
> PR : 사용자 즐겨찾기 디자인 변경 및 각종 설정 변경

- src/components/admin/AdminTour.tsx
- src/components/admin/AdminTraffic.tsx
어색하게 보이는 부분이나 불편한 부분을 개선
1. 행사정보는 카드로 대체
2. 교통지도 범례 켜고끌 수 있는 버튼 추가
> PR : 관리자 모바일 화면 개선

- src/components/admin/AdminComponent.tsx
- src/components/admin/AdminTour.tsx
- src/components/admin/AdminTraffic.tsx
- src/components/stars/dashboard/DashboardComponent.tsx
- src/components/stars/dashboard/TrafficInfoCard.tsx
- src/components/stars/map/AreaFocusCard.tsx
- src/components/user/Info/UserInfo.tsx
- src/components/user/Info/UserInfoEdit.tsx
- src/context/PlaceContext.tsx
대시보드 : 지도 추가 -> 이상한 업데이트가 계속 발생중
마이페이지 : 정보 수정 디자인 변경
> PR : 사용자 대시보드 & 마이페이지 수정

- src/components/admin/TrafficMapComponent.tsx
- src/components/admin/TrafficMapComponentDemo.tsx
- src/components/stars/dashboard/DashboardComponent.tsx
- src/components/stars/dashboard/TrafficInfoCard.tsx
> Feat: TrafficMapComponentDemo 생성

- src/api/searchApi.tsx
- src/components/admin/AdminUserFavorite.tsx
- src/components/stars/map/AreaFocusCard.tsx
- src/components/stars/map/MapSectionComponent.tsx
- src/components/stars/map/SearchBar.tsx
Feat: 팝업에서 자세히 보기, 전화번호, 카카오맵 추가 및 구현
> Feat: 팝업에서 자세히 보기, 전화번호, 카카오맵 추가 및 구현

- src/components/stars/dashboard/ChartCard.tsx
데이터가 없을땐 없다고 표시,
가로(시간) 세로(인구수) 포멧 수정
> Feat: 유동인구수 카드 기능 추가 구현

- src/components/stars/dashboard/AccidentAlertCard.tsx
- src/components/stars/dashboard/DashboardComponent.tsx
- src/components/stars/dashboard/TrafficInfoCard.tsx
> Feat: AccidentAlertCard 틀 생성

- src/components/admin/AdminTour.tsx
- src/components/admin/cards/ForecastPopulationCard.tsx
- src/components/user/Favorite/UserFavorite.tsx
- src/components/user/MyPageComponent.tsx
관리자 화면 -> 모바일 화면에서 잘 보이도록 수정
마이페이지 -> 전체적인 디자인 다듬고 화면 가득차도록 변경
> PR : UI/UX 수정

- src/components/admin/TrafficMapComponentDemo.tsx
+ 범례 삽입
+ 대시보드 스크롤 시 지도 비활성화
+ 대시보드 비활성화 시 Blur 처리
! 주차장마커 overflow 해결
> Feat: Client TrafficMap 수정

- src/components/admin/TrafficMapComponentDemo.tsx
- src/components/stars/dashboard/DashboardComponent.tsx
- src/components/stars/dashboard/TrafficInfoCard.tsx
+TrafficMapComponentDemo: accidentData 활용하여 지도 내에 사건 및 사고 아이콘 표시
+TrafficMapComponentDemo: trafficData.road_traffic_spd 활용하여 해당 관광특구 교통 평균속도 출력
> Feat: 사고 정보 대시보드 지도 출력, 관광특구 평균 속도 출력

- src/components/stars/dashboard/AccidentAlertCard.tsx
- src/components/stars/dashboard/DashboardComponent.tsx
- src/components/stars/dashboard/RatesCard.tsx
- RatesCard BarChart 내 Tooltip 제거
+ 사건 사고 없을 시 '없음' SVG 아이콘 포함
- 대시보드 내 상권카드 주석처리
> Feat: Accident SVG 아이콘 추가

- src/components/admin/cards/AreaNameCard.tsx
- src/components/admin/cards/AreaPopulationCard.tsx
- src/components/admin/cards/CongestionCard.tsx
- src/components/admin/cards/ForecastPopulationCard.tsx
- src/components/admin/cards/PieCard.tsx
- src/components/admin/cards/PopulationRateCard.tsx
- src/components/admin/cards/WeatherCard.tsx
기존 차트 디자인을 개선하고, 각 카드명 왼쪽에 accent를 추가하여 제목을 강조
부제목을 제목 오른쪽으로 옮겨서 보다 컴펙트하게 구성
> PR : 관리자 상세보기 페이지 디자인 변경

- src/components/admin/AdminTour.tsx
- src/components/alert/AccidentModal.tsx
- src/components/stars/map/MapSectionComponent.tsx
사용자 지도 화면에서도 모든 지역의 사고혼잡 정보를 확인할 수 있는 모달 추가
해당 지역특구 선택이 이동도 가능
> PR : 사용자 지도 사고혼잡 전체 모달 추가

- index.html
- src/components/stars/map/MapSectionComponent.tsx
- src/utils/mapbox.tsx
flyTo가 비동기 메소드라 비동기 처리가 가능한 로직 추가
> Fix : 몇몇 검색지역 날라갈 때 화면 죽는 현상 해결

- src/components/stars/dashboard/CulturalEventCard.tsx
- src/components/stars/dashboard/CulturalEventSlider.tsx
- src/components/stars/dashboard/DashboardComponent.tsx
> Feat: 문화행사 카드 구현

- .github/workflows/deploy.yml
- package-lock.json
- package.json
- src/api/suggestionApi.tsx
- src/components/admin/AdminUserInsight.tsx
- src/components/admin/AdminUserManage.tsx
- src/components/stars/map/MapSectionComponent.tsx
- src/components/stars/map/PlaceSuggestion.tsx
- src/components/stars/map/suggestion/PlaceSuggestionShow.tsx
- src/components/stars/map/suggestion/TravelItineraryParser.ts
- src/components/stars/map/suggestion/TravelPlanPreview.tsx
- src/components/stars/map/suggestion/UserPlaceSuggestion.tsx
- src/data/TravelItineraryTypes.ts
> PR : 관광지 추천 AI 버튼 추가

- src/components/admin/AdminTour.tsx
- src/components/admin/AdminUserFavorite.tsx
- src/components/admin/AdminUserManage.tsx
- src/components/stars/map/suggestion/PlaceSuggestionShow.tsx
관리자 페이지중 사용자, 축제화면에 테이블 모드일 때 페이징 기능 추가
> PR : 페이징 기능 추가

- src/components/admin/AdminComponent.tsx
- src/components/admin/AdminTour.tsx
- src/components/admin/AdminTraffic.tsx
- src/components/admin/AdminUserFavorite.tsx
- src/components/admin/AdminUserManage.tsx
- src/components/admin/cards/AccidentCard.tsx
> PR : 관리자 페이지 디자인 수정

- src/components/admin/AdminUserManage.tsx
- src/components/stars/map/CustomControl.ts
- src/components/stars/map/MapSectionComponent.tsx
- src/components/user/Favorite/UserFavorite.tsx
- src/components/user/Info/UserInfo.tsx
계정삭제시 확인을 2번할 수 있는 기능 추가
즐겨찾기는 삭제하고자 하는 장소를 확인시키는 기능 추가
> PR : 삭제 관련 모달 추가

- src/components/admin/AdminTraffic.tsx
- src/components/admin/AdminUserManage.tsx
- src/components/stars/map/suggestion/PlaceSuggestionShow.tsx
- src/utils/jwtUtil.tsx
1. 로그인 바꾸면서 강제 로그아웃 되던 현상 해결
2. 관리자 유저 페이지 검색창 한글자씩만 입력되던 현상 해결
> PR : 버그 수정

- src/components/alert/FavoriteAlertModal.tsx
- src/components/stars/map/MapSectionComponent.tsx
- src/hooks/useFavorites.ts
- src/hooks/useMapMarkers.ts
- src/hooks/useMapboxInit.ts
- src/utils/popupUtils.ts
Refactor: MapSection컴포넌트 분리 및 유지보수 향상
> Refactor: MapSection컴포넌트 분리 및 유지보수 향상

- src/api/mypageApi.tsx
- src/components/stars/map/CustomPopupCard.tsx
- src/components/stars/map/MapSectionComponent.tsx
- src/hooks/useMapMarkers.ts
버튼이 이상하게 뜨거나 추가삭제 로직이 제대로 작동하지 않은 것 수정
> Fix : 지도 즐겨찾기 버그 수정

- src/components/admin/AdminComponent.tsx
- src/components/admin/AdminComponentInsight.tsx
- src/components/admin/AdminTour.tsx
- src/components/admin/AdminTraffic.tsx
- src/components/admin/AdminUserFavorite.tsx
- src/components/admin/AdminUserInsight.tsx
- src/components/admin/AdminUserManage.tsx
- src/components/admin/TrafficMapComponent.tsx
- src/components/admin/cards/AccidentCard.tsx
indigo 색깔로 통일시키고, svg-path로 만들어진 아이콘을 lucide-react를 사용
> PR : 관리자 페이지 색상 변경

- src/components/stars/map/CustomPopupCard.tsx
- src/hooks/useMapMarkers.ts
1. 모달 처리 함수가 빠져있었음
2. 즐겨찾기 등록, 삭제가 2번씩 작동했다
> Fix : 즐겨찾기 등록/삭제시 모달 안뜨던 문제 해결

- src/components/admin/AdminComponentInsight.tsx
- src/components/admin/AdminTour.tsx
- src/components/admin/cards/AccidentCard.tsx
- src/components/admin/cards/CongestionTag.tsx
- src/components/alert/AccidentModal.tsx
- src/components/alert/AlertModal.tsx
- src/components/stars/map/CustomControl.ts
- src/components/user/Favorite/UserFavoriteUtils.tsx
- src/components/user/Info/UserInfoShow.tsx
- src/components/user/MyPageComponent.tsx
- src/context/AdminContext.tsx
기존 이모지로 만들어놨던 것들을 lucide-react를 사용해 통일감을 주고, 색상 및 두께 조절
> PR : 이모지 lucide-react 적용
